apiVersion: v1
kind: Pod
metadata:
  name: x00-demo
spec:
  containers:
  - name: myapp
    image: alpine
    command: ["sleep", "3600"]
  - name: x00
    image: your-registry/x00:latest
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN", "BPF", "SYS_PTRACE"]
